
project:
  name: epl-gw2-predictor
data:
  league_code: E0
  seasons:
    - 2010
    - 2011
    - 2012
    - 2013
    - 2014
    - 2015
    - 2016
    - 2017
    - 2018
    - 2019
    - 2020
    - 2021
    - 2022
    - 2023
    - 2024
  min_matches_per_team: 8
features:
  rolling_window: 8
  include_odds: false
elo:
  k_factor: 20.0
  home_advantage: 60.0
model:
  type: logistic_regression
  cv_folds: 5
  random_state: 42
predict:
  season: 2025
  matchday: 2
